### ISSUE TITLE
Configure custom color maps in xcube server

### ISSUE THREAD

**Issue by forman** [xcube-dev/xcube#1046]
**Is your feature request related to a problem? Please describe.**

Since xcube 1.6, xcube server accepts custom color maps from xcube viewer. We want to allow configuring the same type of custom color maps in xcube server, namely

- Continuous
- Stepwise
- Categorical

**Describe the solution you'd like**

```yaml
CustomColorMaps:
  - Identifier: my_categorical_cmap
    Type: categorical     # or continuous, stepwise 
    Colors:
    - Value: 0
      Color: red
      Label: low
    - Value: 1
      Color: #0000FF
      Label: medium
    - Value: 2
      Color: 0,0,255
      Label: high
  - ...
```

EDIT:

An entry in the in the `Colors` list may have one of the following forms (TypeScript notation):

```ts

type ColorEntry = ColorEntryObj | ColorEntryTuple;

interface ColorEntryObj {
  Value: number;
  Color: Color;
  Label?: string;
}

type ColorEntryTuple = [number, Color] | [number, Color: label];

type Color = ColorName | ColorHex | ColorTuple;
type ColorName = <A CSS color name>; 
type ColorHex = <A CSS color in hexdecimal form>;
type ColorTuple = [number, number, number] | [number, number, number, number]
```

**Comment by forman** [comment]
Here is another practical example:

```yaml
CustomColorMaps:
  - Identifier: my_categorical_cmap
    Type: categorical     # or continuous, stepwise 
    Colors:
    - [ 0, red,     no data]
    - [ 1, yellow,  defective]
    - [ 2, black,   dark area pixels]
    - [ 3, gray,    cloud shadows]
    - [ 4, green,   vegetation]
    - [ 5, tan,     bare soils]
    - [ 6, blue,    water]
    - [ 7, #aaaabb, clouds low prob ]
    - [ 8, #bbbbcc, clouds medium prob]
    - [ 9, #ccccdd, clouds high prob]
    - [10, #ddddee, cirrus]
    - [11, #ffffff, snow or ice]
```

**Comment by forman** [comment]
@konstntokas, I just tested PR #1055 with a real-life server configuration and I see several problems, therefore I reopened the issue: 

- The most important use case of the `CustomColorMaps` is creating categorical color maps. But the endpoint `/colorbars` drops the labels from the color entries.
- `CustomColorMaps` are only returned by the server if they are actually used in the current configuration. That was not the intention. The server must publish all custom color maps for use by the viewer and other clients.
- Why do you use `CustomColorBar` instead of the existing `ColorBar` key in a `ColorMappings` value? `ColorBar` should be fine, because `CustomColorMaps` should be treated like "normal" color maps.

I'm sorry that I didn't discover the problems during my PR which concentrated on plain code review rather than on practical experience.

**Comment by forman** [comment]
Proof for my point 2: `/colorbars` returns 

```json
[ 
  "Custom", 
  "Custom colormaps, e.g. loaded from SNAP *.cpd files or defined via the xcube server config file.",
  [ 
    [
      "s2_l2_scl", 
      "iVBORw0KGgoAAAA...kSuQmCC", 
      { 
        "name": "s2_l2_scl", 
        "type": "categorical", 
        "colors": [ 
          [ 0, "red" ], [ 1, "yellow" ], [ 2, "black" ], [ 3, "gray" ], [ 4, "green" ], [ 5, "tan" ], [ 6, "blue" ], 
          [ 7, "#aaaabb" ], [ 8, "#bbbbcc" ], [ 9, "#ccccdd" ], [ 10, "#ddddee" ], [ 11, "#ffffff" ] ] 
      } 
    ] 
  ] 
]
``` 

for 

```yaml
CustomColorMaps:
  - Identifier: s2_l2_scl
    Type: categorical
    Colors:
    - [ 0, red,     no data]
    - [ 1, yellow,  defective]
    - [ 2, black,   dark area pixels]
    - [ 3, gray,    cloud shadows]
    - [ 4, green,   vegetation]
    - [ 5, tan,     bare soils]
    - [ 6, blue,    water]
    - [ 7, "#aaaabb", clouds low prob ]
    - [ 8, "#bbbbcc", clouds medium prob]
    - [ 9, "#ccccdd", clouds high prob]
    - [10, "#ddddee", cirrus]
    - [11, "#ffffff", snow or ice]
```
